FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    libgl1-mesa-glx \          
    libglib2.0-0 \             
    libsm6 \
    libxext6 \
    libxrender-dev \
    build-essential && \
    apt-get clean

RUN pip3 install --no-cache-dir \
    tensorflow \
    opencv-python-headless \
    flask \
    scipy \
    pymongo

WORKDIR /usr/src/app

EXPOSE 3000
